// This file is auto-generated by CI. Do not edit manually.
import type { Checksums } from './types';

export const CHECKSUMS: Checksums = {
  "darwin_arm64": "6147bc3fda1a5a22ba717d938b59959db98fa03e2894a9b9eeab13e751bccad1",
  "darwin_x86_64": "7eb306e472cd2094db4475b8dd9a063903690a23a65f2ee5c1ea34fcb87c47ba",
  "linux_arm64": "1649d3e5278be5ece6790e124bc59d93b1882737818b9fa5441f08e978fc1a92",
  "linux_x86_64": "ea0baa6f26fa5429622b05bb3aac64e137fba8fd9973c9d01aa3107902a3bd25",
  "windows_x86_64": "58d13ab2bc719989aeec0c86d262fb7bab3a2d71894ce28f86addac17ece58c4"
};
