// This file is auto-generated by CI. Do not edit manually.
import type { Checksums } from './types';

export const CHECKSUMS: Checksums = {
  "darwin_arm64": "875a07a742fb4878aeecaf9036ec5a8e36a27459816d6459fdcd381b39e4ffe7",
  "darwin_x86_64": "cb9bebdac533fb7d1679b879cdaa3c09eb236460d476cd7656fb100beeaa9ac8",
  "linux_arm64": "61536f4e661c5542eafc3f29990fcf1039b1040a0f0cc2295847bd9c95c860d5",
  "linux_x86_64": "3516844796fe644fcd8fce54e28d71b718bcc5bcf1f88c7fe079df772cfef13c",
  "windows_x86_64": "43256044f4fae71a4ff10cd2a027b5a370ff7a756a1497c946c87319f6853c58"
};
