// This file is auto-generated by CI. Do not edit manually.
import type { Checksums } from './types';

export const CHECKSUMS: Checksums = {
  "darwin_arm64": "839b2dbfe818fdc914febb92dafd44f2d4f83bb3a147dd4a62e7bd1787d4c218",
  "darwin_x86_64": "5a90b9fada3aeab624125a3dace0e6f619a550befebcdea92026ec461c746575",
  "linux_arm64": "b6776fc190d9a9b52561b430b31f8bcccb6d2e330345dd74f10aee2011fd9a75",
  "linux_x86_64": "c8d199365854f66384404c99919490599b68d135773a2a46af77050fecf217d3",
  "windows_x86_64": "dd929f2534e84f5e1235f75841e464f125cf7aad3c17548a06665fb8d5f0c445"
};
