// This file is auto-generated by CI. Do not edit manually.
import type { ReleaseInfo } from './types';

export const RELEASE_INFO: ReleaseInfo = {
  version: '0.0.36',
  commitSha: '62d9532adeb746b303360370e478e44233756971',
};
