// This file is auto-generated by CI. Do not edit manually.
import type { ReleaseInfo } from './types';

export const RELEASE_INFO: ReleaseInfo = {
  version: '0.0.36',
  commitSha: '1a24d1a3cca7551c9adf53c61413ce59a5a9e6ef',
};
