// This file is auto-generated by CI. Do not edit manually.
import type { ReleaseInfo } from './types';

export const RELEASE_INFO: ReleaseInfo = {
  version: '0.0.36',
  commitSha: 'd73743b0a8b6481ddce5e595a15323171710b17f',
};
