codecov:
  # Global options
  notify:
    require_ci_to_pass: yes

coverage:
  # Set the global coverage target to a low percentage (e.g., 20%)
  precision: 2
  round: down
  range: "0...20"

  status:
    project:
      # Allow any drop in coverage for the project
      default:
        threshold: 100%
        target: 0%
        paths:
          - "*/"
    patch:
      # Allow any drop in coverage for patches (PRs)
      default:
        threshold: 100%
        target: 0%
        paths:
          - "*/"

  changes:
    # Do not fail the build on coverage changes
    default:
      fail_below: false
